apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-gateway
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-gateway
  template:
    metadata:
      labels:
        app: cloud-gateway
    spec:
      containers:
      - name: gateway
        image: ghcr.io/haema-dev/cloud-gateway:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
        # livenessProbe:
        #   httpGet:
        #     path: /ping
        #     port: 8080
        #   initialDelaySeconds: 30
        #   periodSeconds: 21600      # 6시간 (하루 4번)
        #   timeoutSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /ping
        #     port: 8080
        #   initialDelaySeconds: 15
        #   periodSeconds: 21600      # 6시간 (하루 4번)