apiVersion: v1
kind: Service
metadata:
  name: cloud-gateway-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app: cloud-gateway
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080 # VM 1의 Cloudflared가 바라볼 타겟 포트