apiVersion: v1
kind: Service
metadata:
  name: cloud-frontend-svc
  namespace: default
spec:
  type: ClusterIP # 외부 노출 금지 (Gateway만 접근 가능)
  selector:
    app: cloud-frontend
  ports:
    - port: 80 # Gateway가 찌를 포트 (Service 입구)
      targetPort: 80 # 프론트엔드 컨테이너(Nginx)의 실제 포트 (Service 출구)