spring:
  application:
    name: way

management:
  endpoints:
    web:
      exposure:
        include: "health,gateway"
  endpoint:
    gateway:
      access: read-only
    health:
      # K8s Liveness/Readiness 프로브를 위한 정밀 진단 활성화
      probes:
        enabled: true

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    gate.way: DEBUG